server:
  port: 8080
spring:
  application:
    name: mq-test-rabbit
  rabbitmq:
    addresses: 192.168.229.133:5672
    username: guest
    password: guest
    virtual-host: /
    connection-timeout: 15000
    publisher-confirms: true            # 启用监听消息是否投递成功
    publisher-returns: true             # 启用监听不可路由的消息，就是监听发送失败的消息
    template:
      mandatory: true                   # 如果为true，监听器则接收路由不可达的消息，如果为false Broker端自动删除该消息，监听器接收不到
    listener:
      simple:
        acknowledge-mode: manual        # 手动确认消息
        concurrency: 5                  # 初始化时消费者数量
        max-concurrency: 10             # 初始化时最大消费者数量
        retry:
          enabled: true                 # 开启消费者重试
          max-attempts: 5               # 消息消费最大重试次数
          initial-interval: 5000        # 重试间隔时间（单位毫秒）
        default-requeue-rejected: false # 重试次数超过上面的设置之后是否丢弃（false不丢弃时消息将会入死信队列，注意：死信队列要配置的）  
      # 自定义的配置  
      user:
        exchange:
          name: test.boot.exchange.topic.user
          durable: false
          type: topic
          ignoreDeclarationExceptions: true
        queue:
          name: test.boot.queue.topic.user
          durable: false
        key: test.boot.queue.topic.*
  # Spring Cloud Stream 相关配置，更详细的配置：https://github.com/spring-cloud/spring-cloud-stream-binder-rabbit
  cloud:
    stream:
      binders:
        rabbit_cluster:                                 # 集群配置的key（名称），可以随便起            
          type: rabbit                                  # MQ的类型 
          environment:                                  # MQ的连接配置
            spring:
              rabbitmq:
                addresses: 192.168.229.133:5672
                virtual-host: /
                username: guest
                password: guest
      bindings:
        # 生产端管道相关配置        
        output_channel:                                 # 生产端管道的key（名称），可以随便起      
          binder: rabbit_cluster                        # 绑定集群配置（就是要使用哪个集群配置）
          destination: test.spring.exchange.topic.bean  # 交换机名称
          group: test.spring.queue.topic.bean           # 队列名称 
        # 消费端管道相关配置
        input_channel:                                  # 消费端管道的key（名称），可以随便起  
          binder: rabbit_cluster                        # 绑定集群配置（就是要使用哪个集群配置）
          destination: test.spring.exchange.topic.bean  # 交换机名称
          group: test.spring.queue.topic.bean           # 队列名称 
          consumer:
            concurrency: 1                              # 初始化时消费者数量
      # RabbitMQ 自有特性相关配置      
      rabbit:
        bindings:
          # 消费者端管道自有特性配置    
          input_channel:                                # 管道的名称（就是以下配置要作用到哪个管道上去）
            consumer:                                   # 消费端
              max-concurrency: 10                       # 初始化时最大消费者数量
              requeue-rejected: false                   # false不丢弃时消息将会入死信队列，注意：死信队列要配置的
              acknowledge-mode: manual                  # 手动确认消息
              recovery-interval: 3000                   # 自动重连间隔时间
              durable-subscription: false               # 启用次持久化订阅
